USE [master]
GO

/****** Object:  Database [LojaDsco]    Script Date: 21/02/2019 11:56:44 ******/
CREATE DATABASE [LojaDsco]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LojaDsco', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER12\MSSQL\DATA\LojaDsco.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LojaDsco_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER12\MSSQL\DATA\LojaDsco_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LojaDsco] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LojaDsco].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LojaDsco] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LojaDsco] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LojaDsco] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LojaDsco] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LojaDsco] SET ARITHABORT OFF 
GO

ALTER DATABASE [LojaDsco] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LojaDsco] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LojaDsco] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LojaDsco] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LojaDsco] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LojaDsco] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LojaDsco] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LojaDsco] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LojaDsco] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LojaDsco] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LojaDsco] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LojaDsco] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LojaDsco] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LojaDsco] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LojaDsco] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LojaDsco] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LojaDsco] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LojaDsco] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LojaDsco] SET  MULTI_USER 
GO

ALTER DATABASE [LojaDsco] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LojaDsco] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LojaDsco] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LojaDsco] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LojaDsco] SET  READ_WRITE 
GO


